# change the followings to match your Github username and repo name
baseurl: "/carlosadir" # the name of your github repo
url: "https://carlos-adir.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "Carlos Adir Personal Website"
description: This is the website for Carlos Adir

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Carlos Adir
author-bio: Mechanical Engineer  # change to false to hide
author-image: carlossquare.png  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: Resume
  permalink: resume
- text: About
  permalink: about
- text: Portfolio
  permalink: portfolio
- text: Blog
  permalink: blog

# use false to turn off any social media links
twitter: False
facebook: False
instagram: https://www.instagram.com/carlos.adir.leite
github: https://github.com/carlos-adir
linkedin: https://www.linkedin.com/in/carlos-adir/
medium: False
google-scholar: False
email: False # carlos.adir.leite@gmail.com

# footer information
footer-msg: False # "Powered by Tailpages"
footer-msg-link: False # https://github.com/harrywang/tailpages

# google analytics
google-analytics: G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
